export type BackgroundEntry = {
  name: string;
  description: string;
  characteristic: string;
  stamina: number;
  trait: string;
  expertises: string;
  equipment: string;
  page: number;
};

export const backgroundEntries: BackgroundEntry[] = [
  { name:"Acolyte of the Gardner", description:"You served the god of nature.", characteristic:"Mind", stamina:5, trait:"Enchantment: Material Transfer", expertises:"Athletics, Handle Pet, Nature Lore, Navigate, Religious Lore, Benefaction (2 uses), Elemental (2 uses)", equipment:"Holy symbol, torch, spellbooks: fire hands, minor healing, spark", page:2 },
  { name:"Acolyte of the Healer", description:"You served the god of healing.", characteristic:"Mind", stamina:7, trait:"Benefaction: Enhanced Healing", expertises:"Alchemy, Lift, Religious Lore (2 uses), Benefaction (2 uses)", equipment:"Holy symbol, surgical kit, torch, spellbooks: minor blessing, minor healing", page:2 },
  { name:"Acolyte of the Smith", description:"You served the god of creativity.", characteristic:"Mind", stamina:7, trait:"Enchantment: Hands for Tools", expertises:"Alchemy, Blacksmithing (2 uses), Enchanting, Religious Lore, Benefaction", equipment:"Blacksmith’s tools, holy symbol, torch, spellbooks: minor healing, summon object", page:2 },
  { name:"Acolyte of the Three", description:"You served the god of death, greed, and knowledge.", characteristic:"Mind or Strength", stamina:7, trait:"Necromancy: Soul Absorption", expertises:"Magic Lore, Monster Lore, Religious Lore, Necromancy (2 uses), Chopping", equipment:"Axe, torch, spellbooks: bone capture, minor curse, monster sense", page:2 },
  { name:"Acolyte of the Warrior", description:"You served the god of war.", characteristic:"Mind or Strength", stamina:9, trait:"Benefaction: First Responder", expertises:"Religious Lore, Benefaction, Chopping", equipment:"Axe, holy symbol, torch, spellbooks: minor healing, minor ward", page:2 },
  { name:"Alchemist", description:"You crafted and sold acids, potions, and bombs.", characteristic:"Mind", stamina:5, trait:"Alchemy: Midnight Oil", expertises:"Alchemy (2 uses), Enchanting, Magic Lore, Monster Lore, Nature Lore, Search, Thievery (2 uses)", equipment:"Acid vial, alchemist’s tools, bucket, healing potion, lantern, oil flask, smoke bomb", page:2 },
  { name:"Apprentice Mage", description:"You studied several magic disciplines under a more experienced tutor.", characteristic:"Mind", stamina:5, trait:"Alteration: Alteration Stone", expertises:"Enchanting, Magic Lore, Monster Lore, Alteration (2 uses), Conjuration, Elemental (2 uses), Illusion", equipment:"Alteration stone, spellbooks: jaunt, light, spark, take shape, thunder", page:2 },
  { name:"Archer", description:"You served as a soldier or watch member specially trained with a bow.", characteristic:"Agility", stamina:7, trait:"Archery: Point Blank", expertises:"Athletics, Stealth (2 uses), Bow (2 uses), Unarmed", equipment:"Bear trap, quiver of arrows, shortbow, spyglass, torch", page:2 },
  { name:"Assassin", description:"You were a contract killer or served a higher purpose in a shady organization.", characteristic:"Agility", stamina:5, trait:"Thievery: Sieze the Advantage", expertises:"Athletics, Gymnastics, Stealth (2 uses), Thievery, Bow (2 uses), Slashing (2 uses)", equipment:"Extra knife, poison vial, quiver of arrows, shortbow, torch", page:3 },
  { name:"Beggar", description:"You relied on strangers’ kindness to scrape together enough to live.", characteristic:"Any", stamina:7, trait:"Leverage: More for Less", expertises:"Endurance, Lift, Search (2 uses), Stealth (2 uses)", equipment:"Gluepot, padlock, pot, string, tent, torch", page:3 },
  { name:"Blacksmith", description:"You forged and sold items made from metal.", characteristic:"Strength", stamina:7, trait:"Smithing: Double Duty", expertises:"Blacksmithing (2 uses), Endurance, Lift, Thievery, Bashing", equipment:"Bear trap, blacksmith’s tools, chain, maul, torch", page:3 },
  { name:"Bodyguard", description:"You protected a person of importance.", characteristic:"Strength", stamina:9, trait:"Armor: Interposing Arm", expertises:"Endurance, Search, Slashing", equipment:"Ball bearings, light armor, shield, sword, torch", page:3 },
  { name:"Cartographer", description:"You mapped villages, ruins, and wilderness so others could find their way.", characteristic:"Mind", stamina:7, trait:"Travel: Orienteering", expertises:"Historical Lore, Monster Lore, Nature Lore, Navigate (2 uses), Search", equipment:"Compass, journal, lantern, lore book (Historical Lore), oil flask, quill and inkpot", page:3 },
  { name:"Conjurer", description:"You studied conjuration magic.", characteristic:"Mind", stamina:7, trait:"Conjuration: Jumper", expertises:"Handle Pet, Magic Lore, Monster Lore, Navigate, Conjuration (2 uses)", equipment:"Chain, torch, spellbooks: jaunt, summon object, teleport object", page:3 },
  { name:"Cook", description:"You worked as a cook at a tavern or organization.", characteristic:"Any", stamina:7, trait:"Camping: Hearty Meals", expertises:"Alchemy, Endurance, Lift, Nature Lore (2 uses), Slashing", equipment:"Cook’s utensils, hearty ration (2), pot, torch", page:3 },
  { name:"Duelist", description:"You dedicated your youth to fencing in noble courts.", characteristic:"Agility", stamina:9, trait:"Slashing: Finesse the Blade", expertises:"Gymnastics, Historical Lore, Slashing", equipment:"Light armor, lore book (Historical Lore), mirror, sword, torch", page:3 },
  { name:"Entertainer", description:"You were an acrobat, dancer, and/or musician.", characteristic:"Agility", stamina:5, trait:"Camping: Song of Rest", expertises:"Athletics (2 uses), Endurance, Gymnastics (2 uses), Handle Pet, Historical Lore, Thievery (2 uses)", equipment:"11-foot pole, mirror, musical instrument (lute), smoke bomb, torch", page:4 },
  { name:"Executioner", description:"You carried out capital punishment.", characteristic:"Strength", stamina:9, trait:"Chopping: Chop ‘Em Down", expertises:"Lift, Chopping, Unarmed", equipment:"Chain, greataxe, ladder, padlock, torch", page:4 },
  { name:"Farmer", description:"You plowed fields and raised animals.", characteristic:"Strength", stamina:7, trait:"Pets: Buddy", expertises:"Blacksmithing, Endurance, Handle Pet (2 uses), Lift, Nature Lore", equipment:"11-foot pole, animal feed (6), goat (pet), pot, torch", page:4 },
  { name:"Gladiator", description:"You fought deadly battles for others’ entertainment.", characteristic:"Strength", stamina:9, trait:"Stabbing: Bury the Point", expertises:"Athletics, Lift, Stabbing", equipment:"Light armor, mirror, pike, rage potion, torch", page:4 },
  { name:"Hunter", description:"You tracked animals in the wild and foraged for food.", characteristic:"Agility", stamina:5, trait:"Travel: Foraging Expert", expertises:"Athletics, Handle Pet (2 uses), Nature Lore (2 uses), Navigate, Stealth, Bow (2 uses)", equipment:"Animal feed (6), bear trap, dog (pet), quiver of arrows, shortbow, torch", page:4 },
  { name:"Hydromancer", description:"You learned elemental spells that create and harness water.", characteristic:"Mind", stamina:7, trait:"Elemental: Water Shield", expertises:"Alchemy, Athletics, Enchanting, Magic Lore, Elemental (2 uses)", equipment:"Gluepot, journal, quill and inkpot, torch, spellbooks: create water, stream", page:4 },
  { name:"Illusionist", description:"You studied illusion magic.", characteristic:"Mind", stamina:5, trait:"Illusion: Lasting Illusion", expertises:"Magic Lore (2 uses), Monster Lore, Search, Stealth (2 uses), Thievery, Illusion (2 uses)", equipment:"Card deck, smoke bomb, whistle, spellbooks: cacophony, light, minor phantasm", page:4 },
  { name:"Keraunomancer", description:"You learned elemental spells that create and harness lightning and thunder.", characteristic:"Mind", stamina:7, trait:"Elemental: Hurl the Storm", expertises:"Blacksmith, Enchanting, Magic Lore (2 uses), Elemental (2 uses), Bashing", equipment:"Mace, net, torch, spellbooks: spark, thunder", page:4 },
  { name:"Knight", description:"You served a noble as a knight, or served no one as a hedge knight.", characteristic:"Strength", stamina:9, trait:"Slashing: Swordplay", expertises:"Handle Pet, Historical Lore, Slashing", equipment:"Animal feed (6), greatsword, lantern, light armor, oil flask, riding horse (pet)", page:5 },
  { name:"Merchant", description:"You traveled from village to village trading your wares.", characteristic:"Mind", stamina:7, trait:"Camping: Plotting", expertises:"Historical Lore (2 uses), Lift, Navigate, Search, Thievery", equipment:"Journal, lantern, merchant’s scales, oil flask, quill and inkpot, 50 extra gold coins", page:5 },
  { name:"Miner", description:"You worked in mines, digging and hauling ore.", characteristic:"Strength", stamina:7, trait:"Leverage: Lasting Light", expertises:"Athletics, Endurance (2 uses), Lift, Navigate, Stabbing", equipment:"Chalk, grappling hook, lantern, oil flask, shovel, warpick", page:5 },
  { name:"Noble", description:"You grew up in a family with wealth and power.", characteristic:"Agility or Mind", stamina:7, trait:"Reputation: Call Daddy", expertises:"Handle Pet, Historical Lore (2 uses), Religious Lore, Stealth, Bow", equipment:"Animal feed (6), lantern, lore book (Historical Lore), oil flask, riding horse (pet), 50 gold coins", page:5 },
  { name:"Pugilist", description:"You made a living battling it out with bare knuckles.", characteristic:"Agility or Strength", stamina:9, trait:"Unarmed: Pack a Punch", expertises:"Athletics, Unarmed (2 uses)", equipment:"Chalk, light armor, lore book (Monster Lore), net, rage potion, torch", page:5 },
  { name:"Pyromancer", description:"You learned elemental spells that create and harness fire.", characteristic:"Mind", stamina:5, trait:"Elemental: Burn Baby", expertises:"Alchemy, Enchanting, Historical Lore, Magic Lore (2 uses), Elemental (2 uses)", equipment:"Magnifying glass, smoke bomb, string, torch, spellbooks: fire hands, fire lance", page:5 },
  { name:"Sage", description:"You studied all subjects with a tutor, many books, or both.", characteristic:"Mind", stamina:5, trait:"Knowledge: Cram", expertises:"Historical Lore (2 uses), Magic Lore, Monster Lore (2 uses), Nature Lore, Navigate, Religious Lore, Thievery", equipment:"Ball bearings, journal, lore book (Monster Lore), lore book (Nature Lore), quill and inkpot, torch", page:5 },
  { name:"Soldier", description:"You served in an army protecting others from wilderness threats.", characteristic:"Strength", stamina:9, trait:"Armor: Stalwart", expertises:"Endurance, Bow, Stabbing", equipment:"Light armor, quiver of arrows, shortbow, spear, torch", page:5 },
  { name:"Thief", description:"You burgled places for money, alone or as part of a guild.", characteristic:"Agility", stamina:5, trait:"Thievery: Stealthy", expertises:"Athletics, Gymnastics (2 uses), Search (2 uses), Stealth (2 uses), Thievery (2 uses)", equipment:"Crowbar, extra knife, grappling hook, lockpick set, smoke bomb, torch", page:6 },
  { name:"Tinkerer", description:"You created magical and mechanical inventions.", characteristic:"Mind", stamina:5, trait:"Knowledge: Improvised Equipment", expertises:"Alchemy (2 uses), Blacksmithing (2 uses), Enchanting, Search, Thievery (2 uses), Chopping", equipment:"Alchemist’s tools, blacksmith’s tools, handaxe, lockpick set, soap, torch", page:6 },
  { name:"Transmuter", description:"You studied alteration magic.", characteristic:"Mind", stamina:5, trait:"Alteration: Lasting Alteration", expertises:"Alchemy, Blacksmithing, Enchanting (2 uses), Magic Lore (2 uses), Thievery, Alteration (2 uses)", equipment:"Chalk, torch, spellbooks: jaunt, animal form, repair, take shape", page:6 },
  { name:"Village Watch", description:"You kept a settlement safe.", characteristic:"Strength", stamina:9, trait:"Armor: Stand Strong", expertises:"Athletics, Search, Stabbing", equipment:"Chain, lantern, light armor, oil flask, padlock, pike, whistle", page:6 },
];
